### PR TITLE
Adding support for Windows machines

### PR DESCRIPTION
**Pull request by benjaminprojas**

### CODE REVIEW

**Comment by getninefiveone** [comment]
Will Windows be consistently supported all the time or was this a limited realease?

**Comment by randomstuart** [comment]
This fix doesn't really work, it still requires that you use C://Users so if it's on another drive i.e. D:, E:, F: like me, you are still out of luck!

The path restriction needs to be completely removed!

I've managed to get it to partially update but it still adds the C drive to the path, i.e. C:\d\Local Sites\mywebsite\logs\apache this was achieved by commenting out lines 202-210 and 244-256. I will look into it some more tomorrow when i have some time.

**Comment by benjaminprojas** [comment]
@randomstuart correct, that is a restriction. I needed to make that happen and didn't have an opportunity to do that yet.

**Comment by randomstuart** [comment]
Hi @benjaminprojas, thanks for the response its much appreciated. 

Do you think that you will be able to sort this anytime soon as I'm in a real pickle as I need to launch a website but i cannot access it for final approval?

**Comment by benjaminprojas** [comment]
I don't think this will be fixed anytime soon unfortunately. My work schedule is very full at the moment.

**Pull request merged**
